export const GET_TENANTS = "GET_TENANTS";
export const GET_TENANT = "GET_TENANT";
export const GET_GROUPS = "GET_GROUPS";
export const GET_PHONE_NUMBERS = "GET_PHONE_NUMBERS";
export const GET_ADMINS = "GET_ADMINS";
export const GET_GROUP = "GET_GROUP";
export const GET_USERS = "GET_USERS";
export const GET_PHONE_NUMBERS_BY_GROUP_ID = "GET_PHONE_NUMBERS_BY_GROUP_ID";
export const GET_LICENSES_BY_GROUP_ID = "GET_LICENSES_BY_GROUP_ID";
export const GET_DEVICES_BY_GROUP_ID = "GET_DEVICES_BY_GROUP_ID";
export const GET_USER = "GET_USER";
export const GET_TRUNK_BY_GROUP_ID = "GET_TRUNK_BY_GROUP_ID";

export const DELETE_TENANT = "DELETE_TENANT";
export const DELETE_TENANT_ADMIN = "DELETE_TENANT_ADMIN";
export const DELETE_GROUP_DEVICE = "DELETE_GROUP_DEVICE";
