export const GET_TENANTS = "GET_TENANTS";
export const GET_TENANT = "GET_TENANT";
export const GET_GROUPS = "GET_GROUPS";
export const GET_PHONE_NUMBERS = "GET_PHONE_NUMBERS";
export const GET_ADMINS_TENANT = "GET_ADMINS_TENANT";
export const GET_GROUP = "GET_GROUP";
export const GET_USERS = "GET_USERS";
export const GET_PHONE_NUMBERS_BY_GROUP_ID = "GET_PHONE_NUMBERS_BY_GROUP_ID";
export const GET_LICENSES_BY_GROUP_ID = "GET_LICENSES_BY_GROUP_ID";
export const GET_DEVICES_BY_GROUP_ID = "GET_DEVICES_BY_GROUP_ID";
export const GET_USER = "GET_USER";
export const GET_TRUNK_BY_GROUP_ID = "GET_TRUNK_BY_GROUP_ID";
export const GET_AVAILABLE_NUMBERS_BY_GROUP_ID =
  "GET_AVAILABLE_NUMBERS_BY_GROUP_ID";
export const GET_ADMINS_GROUP = "GET_ADMINS_GROUP";
export const GET_GROUP_ADMIN_BY_ADMIN_ID = "GET_GROUP_ADMIN_BY_ADMIN_ID";
export const GET_TENANT_ADMIN_BY_ADMIN_ID = "GET_TENANT_ADMIN_BY_ADMIN_ID";
export const GET_USER_SERVICES_BY_USER_ID = "GET_USER_SERVICES_BY_USER_ID";
export const GET_TEMPLATES_OF_TENANT = "GET_TEMPLATES_OF_TENANT";

export const POST_CREATE_GROUP_ADMIN = "POST_CREATE_GROUP_ADMIN";
export const POST_CREATE_GROUP_ADMIN_ERROR = "POST_CREATE_GROUP_ADMIN_ERROR";
export const POST_CREATE_TENANT_ADMIN = "POST_CREATE_TENANT_ADMIN";
export const POST_CREATE_TENANT_ADMIN_ERROR = "POST_CREATE_TENANT_ADMIN_ERROR";
export const POST_ASSIGN_USER_SERVICES = "POST_ASSIGN_USER_SERVICES";
export const POST_ASSIGN_USER_SERVICE_PACKS = "POST_ASSIGN_USER_SERVICE_PACKS";

export const PUT_UPDATE_USER = "PUT_UPDATE_USER";
export const PUT_UPDATE_GROUP_DETAILS = "PUT_UPDATE_GROUP_DETAILS";
export const PUT_UPDATE_GROUP_ADMIN = "PUT_UPDATE_GROUP_ADMIN";
export const PUT_UPDATE_TENANT_ADMIN = "PUT_UPDATE_TENANT_ADMIN";
export const PUT_UPDATE_TRUNK_BY_GROUP_ID = "PUT_UPDATE_TRUNK_BY_GROUP_ID";
export const PUT_UPDATE_TRUNK_BY_GROUP_ID_ERROR =
  "PUT_UPDATE_TRUNK_BY_GROUP_ID_ERROR";
export const PUT_UPDATE_SERVICE_PACKS_BY_GROUP_ID =
  "PUT_UPDATE_SERVICE_PACKS_BY_GROUP_ID";
export const PUT_UPDATE_GROUP_SERVICES_BY_GROUP_ID =
  "PUT_UPDATE_GROUP_SERVICES_BY_GROUP_ID";

export const DELETE_TENANT = "DELETE_TENANT";
export const DELETE_TENANT_ADMIN = "DELETE_TENANT_ADMIN";
export const DELETE_GROUP_DEVICE = "DELETE_GROUP_DEVICE";
export const DELETE_GROUP_ADMIN = "DELETE_GROUP_ADMIN";
export const DELETE_DEASSIGN_USER_SERVICES = "DELETE_DEASSIGN_USER_SERVICES";
export const DELETE_DEASSIGN_USER_SERVICE_PACKS =
  "DELETE_DEASSIGN_USER_SERVICE_PACKS";

export const CLEAR_ERROR_MASSAGE = "CLEAR_ERROR_MASSAGE";
export const CHANGE_STEP_OF_CREATE_TENANT = "CHANGE_STEP_OF_CREATE_TENANT";
export const CHANGE_TYPE_OF_TENANT = "CHANGE_TYPE_OF_TENANT";
export const CHANGE_ID_OF_TENANT = "CHANGE_ID_OF_TENANT";
export const CHANGE_NAME_OF_TENANT = "CHANGE_NAME_OF_TENANT";
export const CHANGE_ADDRESS_OF_TENANT = "CHANGE_ADDRESS_OF_TENANT";
export const CHANGE_ZIP_OF_TENANT = "CHANGE_ZIP_OF_TENANT";
export const CHANGE_CITY_OF_TENANT = "CHANGE_CITY_OF_TENANT";
